---
- name: Ping Test Playbook
  hosts: webserver
  tasks:
    - name: Ping the hosts
      ansible.builtin.ping:
- name: Ping Rocky Linux Playbook
  hosts: rockyservers
  tasks:
    - name: Ping the hosts
      ansible.builtin.ping:
...