---
- name: Instalacion de Nginx
  hosts: webservers
  become: yes
  tasks:
    - name: Servicio Nginx Apagado
      service: #'name=nginx state=started enabled=true'
        name: nginx
        state: stopped
        enabled: true
    - name: Desinstalando Paquete de Nginx
      package:
        name: nginx
        state: absent
...