---
- name: Instalacion de Nginx
  hosts: webservers
  become: yes
  tasks:
    - name: Instalando Paquete de Nginx
      package:
        name: nginx
        state: present
        update_cache: true
    - name: Verificando la existencia del archivo de unidad de servicio de Nginx
      stat:
        path: /lib/systemd/system/nginx.service
      register: nginx_service
    - name: Servicio Nginx Arrancado
      service: #'name=nginx state=started enabled=true'
        name: nginx
        state: started
... 
